### ISSUE TITLE
Optimize tracking

### ISSUE THREAD

**Issue by lennerd** [FH-Potsdam/shifted-maps#48]
- [ ] Remove tracking from repository
- [ ] Track if users use their own dataset or the dataset of someone else
- [ ] Refactore tracking based on the research questions
